$(document).ready(function () {
    $('#map').usmap({
        'stateSpecificHoverStyles': {
            "AL": {fill: '#FF6961'},
            "AK": {fill: '#009F00'},
            "AZ": {fill: '#80FF80'},
            "AR": {fill: '#80FF80'},
            "CA": {fill: '#009F00'},
            "CO": {fill: '#009F00'},
            "CT": {fill: '#80FF80'},
            "DE": {fill: '#80FF80'},
            "FL": {fill: '#80FF80'},
            "GA": {fill: '#80FF80'},
            "HI": {fill: '#80FF80'},
            "ID": {fill: '#FF6961'},
            "IL": {fill: '#009F00'},
            "IN": {fill: '#FF6961'},
            "IA": {fill: '#FF6961'},
            "KS": {fill: '#FF6961'},
            "KY": {fill: '#FF6961'},
            "LA": {fill: '#80FF80'},
            "ME": {fill: '#009F00'},
            "MD": {fill: '#80FF80'},
            "MA": {fill: '#009F00'},
            "MI": {fill: '#009F00'},
            "MN": {fill: '#80FF80'},
            "MS": {fill: '#FF6961'},
            "MO": {fill: '#80FF80'},
            "MT": {fill: '#80FF80'},
            "NE": {fill: '#FF6961'},
            "NV": {fill: '#009F00'},
            "NH": {fill: '#80FF80'},
            "NJ": {fill: '#80FF80'},
            "NM": {fill: '#80FF80'},
            "NY": {fill: '#80FF80'},
            "NC": {fill: '#FF6961'},
            "ND": {fill: '#80FF80'},
            "OH": {fill: '#80FF80'},
            "OK": {fill: '#80FF80'},
            "OR": {fill: '#009F00'},
            "PA": {fill: '#80FF80'},
            "RI": {fill: '#80FF80'},
            "SC": {fill: '#FF6961'},
            "SD": {fill: '#FF6961'},
            "TN": {fill: '#FF6961'},
            "TX": {fill: '#FF6961'},
            "UT": {fill: '#80FF80'},
            "VT": {fill: '#009F00'},
            "VA": {fill: '#FF6961'},
            "WA": {fill: '#009F00'},
            "WV": {fill: '#80FF80'},
            "WI": {fill: '#FF6961'},
            "WY": {fill: '#FF6961'},
            "DC": {fill: '#FF6961'},
        },
        mouseover: function (event, data) {

            $('#tooltip').text(stateName[data.name]).show()
            $('#map').mousemove(function (e) {
                var mouseX = e.pageX - 65;
                var mouseY = e.pageY - 80;
                $('#tooltip').css({
                    top: mouseY,
                    left: mouseX,
                });
            });
        },

        mouseout: function (event, data) {
            $('#tooltip').hide();
        },
        
    });
    // not funtional atm, need to add state laws
    let stateLaw = {
        "AL": "Alabama ",
        "AK": "Alaska ",
        "AZ": "Arizona ",
        "AR": "Arkansas ",
        "CA": "California ",
        "CO": "Colorado ",
        "CT": "Connecticut ",
        "DE": "Delaware ",
        "FL": "Florida ",
        "GA": "Georgia ",
        "HI": "Hawaii ",
        "ID": "Idaho ",
        "IL": "Illinois ",
        "IN": "Indiana ",
        "IA": "Iowa ",
        "KS": "Kansas ",
        "KY": "Kentucky ",
        "LA": "Louisiana ",
        "ME": "Maine ",
        "MD": "Maryland ",
        "MA": "Massachusetts ",
        "MI": "Michigan ",
        "MN": "Minnesota ",
        "MS": "Mississippi ",
        "MO": "Missouri ",
        "MT": "Montana ",
        "NE": "Nebraska ",
        "NV": "Nevada ",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "OH": "Ohio",
        "OK": "Oklahoma ",
        "OR": "Oregon ",
        "PA": "Pennsylvania ",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee ",
        "TX": "Texas ",
        "UT": "Utah ",
        "VT": "Vermont ",
        "VA": "Virginia ",
        "WA": "Washington ",
        "WV": "West Virginia",
        "WI": "Wisconsin ",
        "WY": "Wyoming ",
        "DC": "Washington D.C.",
    }

    let stateName = {
        "AL": "Alabama ",
        "AK": "Alaska ",
        "AZ": "Arizona ",
        "AR": "Arkansas ",
        "CA": "California ",
        "CO": "Colorado ",
        "CT": "Connecticut ",
        "DE": "Delaware ",
        "FL": "Florida ",
        "GA": "Georgia ",
        "HI": "Hawaii ",
        "ID": "Idaho ",
        "IL": "Illinois ",
        "IN": "Indiana ",
        "IA": "Iowa ",
        "KS": "Kansas ",
        "KY": "Kentucky ",
        "LA": "Louisiana ",
        "ME": "Maine ",
        "MD": "Maryland ",
        "MA": "Massachusetts ",
        "MI": "Michigan ",
        "MN": "Minnesota ",
        "MS": "Mississippi ",
        "MO": "Missouri ",
        "MT": "Montana ",
        "NE": "Nebraska ",
        "NV": "Nevada ",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "OH": "Ohio",
        "OK": "Oklahoma ",
        "OR": "Oregon ",
        "PA": "Pennsylvania ",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee ",
        "TX": "Texas ",
        "UT": "Utah ",
        "VT": "Vermont ",
        "VA": "Virginia ",
        "WA": "Washington ",
        "WV": "West Virginia",
        "WI": "Wisconsin ",
        "WY": "Wyoming ",
        "DC": "Washington D.C.",
    }


});



